# Generated by Django 4.2.6 on 2023-10-09 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_bookmark_like_reply_rename_content_feed_feed_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='feed_id',
            new_name='content',
        ),
    ]
